apiVersion: v1
entries:
  helm-guestbook:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-07-30T21:35:53.501956-05:00"
    description: A Helm chart for Kubernetes
    digest: 5928ed116d29aae06268ff93177c0fbd8c1734c94de2897553374fee3c5a0624
    name: helm-guestbook
    type: application
    urls:
    - https://ssrisunt-priv.github.io/helm-blue-green/charts/helm-guestbook-0.1.0.tgz
    version: 0.1.0
generated: "2025-07-30T21:35:53.501175-05:00"
